<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.davidricardo1026</groupId>
        <artifactId>easytrans-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>easytrans-spring-boot2-starter</artifactId>
    <name>easytrans-spring-boot2-starter</name>
    <description>EasyTrans Starter for Spring Boot 2</description>

    <dependencies>
        <dependency>
            <groupId>io.github.davidricardo1026</groupId>
            <artifactId>easytrans-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>2.7.18</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>2.7.18</version>
        </dependency>
    </dependencies>
</project>
