<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>io.github.davidricardo1026</groupId>
    <artifactId>easytrans-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>easytrans-parent</name>
    <description>EasyTrans: High-performance, zero-intrusion auto-translation tool based on MapStruct and AP
    </description>

    <modules>
        <module>easytrans-core</module>
        <module>easytrans-processor</module>
        <module>easytrans-spring-boot-starter</module>
        <module>easytrans-spring-boot2-starter</module>
        <module>easytrans-demo</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <mybatis-plus.version>3.5.10.1</mybatis-plus.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <lombok.version>1.18.30</lombok.version>
    </properties>
</project>
